CREATE TABLE
  `Customers` (
    `CustomerID` char(39) NOT NULL,
    `FirstName` varchar(100) NULL,
    `LastName` varchar(100) NULL,
    `FullName` varchar(200) NULL,
    `Gender` varchar(20) NULL,
    `DateOfBirth` date NULL,
    `Email` varchar(150) NULL,
    `PhoneNumber` varchar(30) NULL,
    `SecondaryPhoneNumber` varchar(30) NULL,
    `AddressLine1` varchar(255) NULL,
    `AddressLine2` varchar(255) NULL,
    `City` varchar(100) NULL,
    `State` varchar(100) NULL,
    `PostalCode` varchar(20) NULL,
    `Country` varchar(100) NULL,
    `TimeZone` varchar(100) NULL,
    `AccountManagerID` char(38) NULL,
    `LeadSource` varchar(100) NULL,
    `CustomerType` varchar(50) NULL,
    `Industry` varchar(100) NULL,
    `CompanyName` varchar(200) NULL,
    `AnnualRevenue` decimal(18, 2) NULL,
    `NumberOfEmployees` int NULL,
    `LastPurchaseDate` date NULL,
    `TotalPurchaseValue` decimal(18, 2) NULL,
    `IsSubscribedToNewsletter` tinyint NULL,
    `PreferredContactMethod` varchar(50) NULL,
    `LastContactedDate` datetime NULL,
    `ContactFrequency` varchar(50) NULL,
    `Notes` varchar(4000) NULL,
    `OptInStatus` tinyint NULL,
    `LastInteractionType` varchar(50) NULL,
    `InteractionScore` int NULL,
    `SupportTicketCount` int NULL,
    `HasOpenTicket` tinyint NULL,
    `SatisfactionScore` int NULL,
    `CampaignID` char(38) NULL,
    `CampaignName` varchar(255) NULL,
    `CampaignStartDate` date NULL,
    `CampaignEndDate` date NULL,
    `CampaignChannel` varchar(100) NULL,
    `CampaignResponse` varchar(100) NULL,
    `ConversionDate` date NULL,
    `PromoCodeUsed` varchar(100) NULL,
    `LeadScore` int NULL,
    `CRMCreatedDate` datetime NULL,
    PRIMARY KEY (`CustomerID` ASC)
  );
